services:
    con4gis.layer_service:
        class: con4gis\MapsBundle\Classes\Services\LayerService
        public: true
        arguments:
            - "@event_dispatcher"
            - "@con4gis.layer_content_service"

    con4gis.profile_service:
        class: con4gis\MapsBundle\Classes\Services\ProfileService
        public: true
        arguments:
            - "@event_dispatcher"

    con4gis.baselayer_service:
        class: con4gis\MapsBundle\Classes\Services\BaseLayerService
        public: true
        arguments:
            - "@event_dispatcher"

    con4gis.layer_content_service:
        class: con4gis\MapsBundle\Classes\Services\LayerContentService
        public: true
        arguments:
            - "@con4gis.profile_service"

    con4gis\MapsBundle\Controller\LayerController:
        class: con4gis\MapsBundle\Controller\LayerController
        public: true
        arguments:
            - "@service_container"

    con4gis\MapsBundle\Controller\BaselayerController:
        class: con4gis\MapsBundle\Controller\BaselayerController
        public: true
        arguments:
            - "@service_container"
